mod common;
use common::{setup_database, tear_down};
use entity::{config, prelude::*, user};
use sea_orm::{ActiveValue::Set, prelude::*};

#[tokio::test]
async fn test_find_by_id() {
    let (container, state) = setup_database().await;
    let root_user = user::ActiveModel {
        account: Set("root2".to_string()),
        password: Set("$2b$12$n7NaDXwHdpCQI5LlsM1viuDJWZWofuhz/HnGAi8X.BmPRIuHvaXUy".to_string()),
        enable: Set(true),
        ..Default::default()
    };
    root_user.insert(&state.conn).await.unwrap();
    let user: Option<user::Model> = User::find()
        .filter(user::Column::Account.eq("root"))
        .one(&state.conn)
        .await
        .unwrap();
    assert!(user.is_some());
    let _ = &state.conn.close().await.unwrap();
    tear_down(container).await;
}

#[tokio::test]
async fn test_email_unique() {
    let (container, state) = setup_database().await;
    let email = "duplicate@example.com".to_string();
    let insert_user = |account: &str| {
        let account = account.to_owned();
        let email = email.clone();
        let conn = state.conn.clone();
        async move {
            user::ActiveModel {
                account: Set(account),
                password: Set(
                    "$2b$12$n7NaDXwHdpCQI5LlsM1viuDJWZWofuhz/HnGAi8X.BmPRIuHvaXUy".to_string(),
                ),
                email: Set(Some(email)),
                enable: Set(true),
                ..Default::default()
            }
            .insert(&conn)
            .await
        }
    };
    insert_user("dup1").await.unwrap();
    let err = insert_user("dup2").await.unwrap_err();
    assert!(
        matches!(err, sea_orm::DbErr::Exec(_) | sea_orm::DbErr::Query(_)),
        "duplicate email should violate unique constraint, got {err:?}"
    );
    let _ = &state.conn.close().await.unwrap();
    tear_down(container).await;
}

#[tokio::test]
async fn test_config_timestamps() {
    let (container, state) = setup_database().await;
    let cfg = config::ActiveModel {
        key: Set("greeting".to_string()),
        value: Set(Some(serde_json::json!({ "hello": "world" }))),
        ..Default::default()
    }
    .insert(&state.conn)
    .await
    .unwrap();
    assert!(!cfg.id.is_empty(), "id should be generated by before_save");
    assert!(
        cfg.create_datetime.is_some(),
        "create_datetime should be set"
    );
    assert!(
        cfg.update_datetime.is_some(),
        "update_datetime should be set"
    );

    let mut updated: config::ActiveModel = cfg.clone().into();
    updated.value = Set(Some(serde_json::json!({ "hello": "vanling" })));
    updated.update(&state.conn).await.unwrap();

    let reloaded: config::Model = Config::find_by_id(cfg.id.clone())
        .one(&state.conn)
        .await
        .unwrap()
        .unwrap();
    assert_eq!(
        reloaded.create_datetime, cfg.create_datetime,
        "create_datetime should be unchanged"
    );
    assert!(
        reloaded.update_datetime.is_some() && reloaded.update_datetime >= cfg.update_datetime,
        "update_datetime should be refreshed on update"
    );
    let _ = &state.conn.close().await.unwrap();
    tear_down(container).await;
}
