base_url = "/"
title = "Vanling"
description = "Vanling 文档"
default_language = "zh"
build_search_index = false
compile_sass = true
generate_feeds = false

slugify = { paths = "on", taxonomies = "on", anchors = "safe" }

[markdown]

[markdown.highlighting]
theme = "catppuccin-latte"
style = "class"

[extra]
repo_url = "https://github.com/lastsunday/vanling"

[languages.en]
build_search_index = false
title = "Vanling"

[languages.en.translations]
description = "Vanling Documentation"
