# https://github.com/78/xiaozhi-fonts
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_14_1-emojis_32.bin -O apps/server/web/device/assets/none-font_puhui_common_14_1-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_14_1-emojis_64.bin -O apps/server/web/device/assets/none-font_puhui_common_14_1-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_14_1-none.bin -O apps/server/web/device/assets/none-font_puhui_common_14_1-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_16_4-emojis_32.bin -O apps/server/web/device/assets/none-font_puhui_common_16_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_16_4-emojis_64.bin -O apps/server/web/device/assets/none-font_puhui_common_16_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_16_4-none.bin -O apps/server/web/device/assets/none-font_puhui_common_16_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_20_4-emojis_32.bin -O apps/server/web/device/assets/none-font_puhui_common_20_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_20_4-emojis_64.bin -O apps/server/web/device/assets/none-font_puhui_common_20_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_20_4-none.bin -O apps/server/web/device/assets/none-font_puhui_common_20_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_30_4-emojis_32.bin -O apps/server/web/device/assets/none-font_puhui_common_30_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_30_4-emojis_64.bin -O apps/server/web/device/assets/none-font_puhui_common_30_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-font_puhui_common_30_4-none.bin -O apps/server/web/device/assets/none-font_puhui_common_30_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-none-emojis_32.bin -O apps/server/web/device/assets/none-none-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-none-emojis_64.bin -O apps/server/web/device/assets/none-none-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/none-none-none.bin -O apps/server/web/device/assets/none-none-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_14_1-emojis_32.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_14_1-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_14_1-emojis_64.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_14_1-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_14_1-none.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_14_1-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_16_4-emojis_32.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_16_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_16_4-emojis_64.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_16_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_16_4-none.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_16_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_20_4-emojis_32.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_20_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_20_4-emojis_64.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_20_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_20_4-none.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_20_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_30_4-emojis_32.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_30_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_30_4-emojis_64.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_30_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-font_puhui_common_30_4-none.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-font_puhui_common_30_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-none-emojis_32.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-none-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-none-emojis_64.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-none-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9s_nihaoxiaozhi-none-none.bin -O apps/server/web/device/assets/wn9s_nihaoxiaozhi-none-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_14_1-emojis_32.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_14_1-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_14_1-emojis_64.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_14_1-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_14_1-none.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_14_1-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_16_4-emojis_32.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_16_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_16_4-emojis_64.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_16_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_16_4-none.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_16_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_20_4-emojis_32.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_20_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_20_4-emojis_64.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_20_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_20_4-none.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_20_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_30_4-emojis_32.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_30_4-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_30_4-emojis_64.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_30_4-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_30_4-none.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-font_puhui_common_30_4-none.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-none-emojis_32.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-none-emojis_32.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-none-emojis_64.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-none-emojis_64.bin
wget https://github.com/78/xiaozhi-fonts/releases/download/assets/wn9_nihaoxiaozhi_tts-none-none.bin -O apps/server/web/device/assets/wn9_nihaoxiaozhi_tts-none-none.bin
